version: '3.8'

services:
  backend:
    build: ./backend
    container_name: discover_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/discoverdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: discover_frontend
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: discover_mongo
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: discover_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
